version: '3'

services:
  node-app:
    build:
      target: dev
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - DB_USER=mugil
      - DB_PASSWORD=password
      - DB_NAME=dev_db

  mysql:
    environment:
      - MYSQL_ROOT_PASSWORD=mypassword
      - MYSQL_DATABASE=dev_db
      - MYSQL_USER=mugil
      - MYSQL_PASSWORD=password
    ports:
      - '3306:3306'
